parrying:
  enabled: true
  parry-time: 250
  parry-chance: 1
  parry-message: '&2*** Parried ***'
  disarm-time: 350
  disarm-chance: 0.3
  disarm-message: '&c*** Disarmed ***'
  fumble-time: 350
  fumble-chance: 0.3
  fumble-message: '&c*** Fumbled weapon ***'
headshots:
  enabled: true
  multiplier: 2
  dealt-message: '&2*** Headshot ***'
  taken-message: '&c*** Headshot ***'
lunging:
  enabled: true
  leap: 1.5
  message: '&c*** Lunged ***'
armored-boats:
  enabled: true
  prevent-boat-litter: true
fast-arrows:
  enabled: true
  speed: 1.5
  disable-damage-increase: true
arrow-retrieval:
  enabled: true
  retrieval-rate: 0.7
antispam-bows:
  enabled: true
  minimum-draw: 750
  message: '&c*** Fumbled arrow ***'
broken-knees:
  enabled: true
  fall-multiplier: 2
  feather-falling: true
assassinations:
  enabled: true
  dealt-message: '&2*** Assassinated ***'
  taken-message: '&c*** Assassinated ***'