parrying:
  enabled: true
  parry-time: 250
  parry-chance: 1
  parry-message: '&2*** Parried ***'
  disarm-time: 350
  disarm-chance: 0.3
  disarm-message: '&c*** Disarmed ***'
  fumble-time: 350
  fumble-chance: 0.3
  fumble-message: '&c*** Fumbled weapon ***'
headshots:
  enabled: true
  multiplier: 2
  dealt-message: '&2*** Headshot on %victim% ***'
  taken-message: '&c*** Headshot from %player% ***'
lunging:
  enabled: false
  leap: 1.5
  message: '&c*** Lunged ***'
armored-boats:
  enabled: true
  prevent-boat-litter: true
fast-arrows:
  enabled: true
  speed: 1.5
  disable-damage-increase: true
arrow-retrieval:
  enabled: true
  retrieval-rate: 0.7
antispam-bows:
  enabled: true
  minimum-draw: 750
  message: '&c*** Fumbled arrow ***'
broken-knees:
  enabled: true
  fall-multiplier: 2
  feather-falling: true
assassinations:
  enabled: true
  warning-time: 500
  warning-message: '&c*** Something is behind you ***'
  death-time: 1000
  dealt-message: '&2*** Assassinated %victim% ***'
  taken-message: '&c*** Assassinated by %player% ***'
ballistae:
  enabled: true
  arrow-flight-speed: 2.5
  fire-charge-flight-speed: 1.5
  cooldown: 2000
  cooldown-message: '&c*** Loading Ballista ***'
  no-ammo-message: '&c*** Nothing to launch ***'
no-durability:
  enabled: true