main: com.amoebaman.combatmods.CombatMods

name: CombatMods
version: 1.4.1
author: AmoebaMan
description: Various additions/adjustments to make combat more fun and/or realistic

commands:
  cmreload:
    description: Reloads values from config.yml
    usage: /cmreload