main: net.amoebaman.combatmods.CombatMods

name: CombatMods
version: 1.3
author: AmoebaMan
description: Various additions/adjustments to make combat more fun and/or realistic
softdepend: [StatMaster]

commands:
  cmreload:
    description: Reloads values from config.yml
    usage: /cmreload